### PR TITLE
feat: force layout support cluster

### PR DESCRIPTION
**Pull request by wFanhua**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by Yanyan-Wang** [comment]
🎊🎊👍👍👍

**Comment by wFanhua** [comment]
> 🎊🎊👍👍👍

check部分怎么才能通过

**Comment by wFanhua** [comment]
后续我应该怎么处理？ @baizn

**Comment by baizn** [comment]
> 后续我应该怎么处理？ @baizn

提到 3.8.2 分支上

**Pull request closed without merging**
