### PR TITLE
chore: update issue template

### PR DESCRIPTION
**Pull request by cliffordfajardo**
## What is the change?
1. Update the `bug_report.yml` github file to enable [Github's new issue template form](https://youtu.be/qQE1BUkf2-s?t=23)
2. Add `config.yml` inside file the `.github/ISSUE_TEMPLATE/` folder
3. Remove `/G6-example-contribution-example.md` and `antv-issue-template.md ` file from `.github/ISSUE_TEMPLATE/` folder` now that there is a `bug_report.yml` file

## Motivation for this code change?
- encourage's bug reporter's to put more care into their bug report before submission
- this may help `G6` maintainer's receive more detailed & higher quality bug report's
- prevents bug reporter from submitting a bug IF they do not fill in the required fields specified in the `bug_report.yml` file
- adds helpful tips for user's during the process of creating a bug/issue report
- encourages community to ask question's inside of [G6's Discussion tab](https://github.com/antvis/G6/issues/3363)

## Example / Demo:
- Demo repository: https://github.com/cliffordfajardo/TEST-ant-g6-issue-template/issues/new/choose

CleanShot 2021-12-12 at 16 43 25@2x

**Issue template example :**
CleanShot 2021-12-12 at 16 44 37@2x

## References
- [Github Docs for templates to encourage useful issues & pull requests](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) 
- [Github Docs for `config.yml` file](https://docs.github.com/en/enterprise-server@3.0/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

### CODE REVIEW

**Comment by cliffordfajardo** [comment]
@Yanyan-Wang @elaine1234 @baizn @pomelo-nwu

We can create a template in Chinese afterward this as well.
We would create a new filed called `bug_report_chinese.yml`
 - I do not speak Chinese so my translations would not be as good 😅

**Comment by Yanyan-Wang** [comment]
Hi @cliffordfajardo, thanks for your pull request!

In the files changed tab, I did not see the config.yml and bug_report.yml. Is there any missing commit?

**Comment by cliffordfajardo** [comment]
@cliffordfajardo - I think I may have forgotten to add it - strange 🤔 
Will add right now 🚀

**Comment by Yanyan-Wang** [comment]
Thanks again. And, I think it is necessary to keep the `G6-example-contribution-example` which is for demo contributions.

**Comment by cliffordfajardo** [comment]
@Yanyan-Wang - I've added a new file `bug_report_chinese.yml`

Apologies for the translation's, I used Google translate to convert the original English text

CleanShot 2021-12-13 at 08 49 59

**Comment by cliffordfajardo** [comment]
Lastly on an unrelated topic
Would you be able to take a look at these 2 very tiny pull requests from @Blakko ? 🙏 
- https://github.com/antvis/G6/pull/3315
- https://github.com/antvis/G6/pull/3322

**Comment by Yanyan-Wang** [comment]
> @Yanyan-Wang - I've added a new file `bug_report_chinese.yml`
> 
> Apologies for the translation's, I used Google translate to convert the original English text
> 
> CleanShot 2021-12-13 at 08 49 59
> 
> Thanks 🙏


Doesn't matter. It is good enough. I will refine the Chinese version later

**Pull request merged**
