### PR TITLE
feat: comboCombined Layout; feat: combo supports position configurations for any situations; 4.6.0-beta

### PR DESCRIPTION
**Pull request by Yanyan-Wang**
- feat: comboCombined Layout from @antv/layout;
- feat: combo supports position configurations for any situations;
- fix: run layout promise only when the layout is configured;

### CODE REVIEW

**Comment by simplejason** [comment]
> feat: combo supports position configurations for any situations;

这个 PR 是否意味着用户在 layout 指定 combo 的 x y 位置后，G6 不会覆盖指定的配置信息呢？

**Comment by cliffordfajardo** [comment]
> feat: comboCombined Layout from @antv/layout;
> feat: combo supports position configurations for any situations;

Hi - [this demo you shared here](https://github.com/antvis/G6/discussions/3435#discussioncomment-2156304) looks awesome 😄 

I did run into some challenges with the `comboCombined` feature. I created a few demo codesandbox's and videos with explanations of me using the new feature with the potential bug
- https://github.com/antvis/G6/issues/3524#issuecomment-1053225851

**Comment by cliffordfajardo** [comment]
Hi @Yanyan-Wang ,

**1. What does this part of the new documentation below mean in practice & what would it allow G6 users to do ?**

> feat: combo supports position configuration for any situation - [documentation link](https://github.com/antvis/G6/pull/3510/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR2)

**2. Do you know if the new feature mentioned below will support specifying `layout: grid` to allow items inside combo to be position in a grid manner?**

> feat: comboCombined Layout from @antv/layout; - [demo from G6 team](https://github.com/antvis/G6/discussions/3435#discussioncomment-2156304)

<details>
<summary>Example 1 (Concept): Combo with grid layout</summary>

Credits to [C.I website for demos below](https://cambridge-intelligence.com/graph-visualization-rectangular-combos/)
CleanShot 2022-02-28 at 14 32 52

combo-with-grid-items-ordered
</details>

**Comment by simplejason** [comment]
> Hi @Yanyan-Wang ,
> 
> **1. What does this part of the new documentation below mean in practice & what would it allow G6 users to do ?**
> 
> > feat: combo supports position configuration for any situation - [documentation link](https://github.com/antvis/G6/pull/3510/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR2)
> 
> **2. Do you know if the new feature mentioned below will support specifying `layout: grid` to allow items inside combo to be position in a grid manner?**
> 
> > feat: comboCombined Layout from @antv/layout; - [demo from G6 team](https://github.com/antvis/G6/discussions/3435#discussioncomment-2156304)
> 
> Example 1 (Concept): Combo with grid layout
> **3. Is this new `dagreCompound` layout going to be part of v4.6?**

`Is this new dagreCompound layout going to be part of v4.6?`

Layout `dagreCompound` will be included in v4.6, you can use it in v4.6 :) But it is a beta version for now and is expected to be converted to release version  in 1-2 minor releases.

**Comment by Yanyan-Wang** [comment]
Hi, @cliffordfajardo 

> 1. What does this part of the new documentation below mean in practice & what would it allow G6 users to do ?

Users are allow to adjust combo positions by graph.updateItem, and then the children of the combo will follow it. Similarly, when user adjust the child node/combo position, the parent combo will follows it too.

> 2. Do you know if the new feature mentioned below will support specifying layout: grid to allow items inside combo to be position in a grid manner?

Yes. Configure the comboCombined layout with innerLayout: new G6.Layout['grid]() will results in this:
image

**Comment by Yanyan-Wang** [comment]
The v4.6.0 is published

> I did run into some challenges with the comboCombined feature. I created a few demo codesandbox's and videos with explanations of me using the new feature with the potential bug

About the bugs or problems, I will keep focusing on them in the later minor releases

**Pull request merged**
