### PR TITLE
Update graph.ts

### PR DESCRIPTION
**Pull request by JeffreyCheungGit**
fix:fix memory overflow issue in vue

### CODE REVIEW

**Comment by Aarebecca** [comment]
Please describe the memory leak problem you have encountered and how this PR solves this problem.

**Comment by JeffreyCheungGit** [comment]
the vue binding data is used as an argument to Graph.data(),Graph.data(data) arg <data> should be de-referenced.发自我的 iPhone在 2023年12月27日，11:21，Aaron ***@***.***> 写道：Please describe the memory leak problem you have encountered and how this PR solves this problem.

**Comment by Aarebecca** [comment]
> the vue binding data is used as an argument to Graph.data(),Graph.data(data) arg <data> should be de-referenced.发自我的 iPhone在 2023年12月27日，11:21，Aaron ***@***.***> 写道：Please describe the memory leak problem you have encountered and how this PR solves this problem. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.

Maybe you can make a deep copy of the data externally, which affects performance when there is a large amount of data.

**Comment by JeffreyCheungGit** [comment]
You are right, that's I'am doing now. But when the memory overflow occurs, there's no clue. Just trying to get it to do more processing.

**Pull request closed without merging**
