### PR TITLE
fix: findAllByState should not select hidden nodes

### PR DESCRIPTION
**Pull request by femiabdul**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Description of change

This PR introduces `additionalFilter` parameter on `findAllByState`. This allows for extra filtering e.g don't select nodes with `visible: false`.

### CODE REVIEW

**Comment by Yanyan-Wang** [comment]
Thanks for your PR!

**Review by Yanyan-Wang — APPROVED** [review]

**Comment by podf** [comment]
如果某个combo中的节点与另一节点之间的线段被设置hover状态，但这个combo被折叠收起。那么他们之间的连线将不会被findAllByState获取到！
If the line segment between a node in a combo and another node is set to hover state, but the combo is collapsed. Then the connection between them will not be obtained by findAllByState!

**Comment by podf** [comment]
> 如果某个combo中的节点与另一节点之间的线段被设置hover状态，但这个combo被折叠收起。那么他们之间的连线将不会被findAllByState获取到！ If the line segment between a node in a combo and another node is set to hover state, but the combo is collapsed. Then the connection between them will not be obtained by findAllByState!

这种情况我们将如何获取重新定义线段的状态，比如取消hover

**Comment by podf** [comment]
> 如果某个combo中的节点与另一节点之间的线段被设置hover状态，但这个combo被折叠收起。那么他们之间的连线将不会被findAllByState获取到！ If the line segment between a node in a combo and another node is set to hover state, but the combo is collapsed. Then the connection between them will not be obtained by findAllByState!


这种情况我们将如何获取重新定义线段的状态，比如取消hover
In this case, how do we get the status of the redefined line segment, such as canceling hover

**Pull request merged**
